### ISSUE TITLE
Service Fabric StatefulService or StatelessService

### ISSUE THREAD

**Issue by nyghtrocker** [vany0114/microservices-dotnetcore-docker-servicefabric#2]
Hi, I'm learning micro services using service fabric. I read different tutorial and they inherit from StatefulService or StatelessService service in service fabric but you don't have any inheritance from StatefulService or StatelessService. why you don't have  inheritance from service fabric?

**Comment by vany0114** [comment]
Hi @nyghtrocker 
That's why I'm using Azure Service Fabric with Docker which is another approach. But of course, you can use the Stateful or Stateless services of SF. In other words, I'm using the [Service Fabric Containers programming model](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-choose-framework#containers). So, you're talking about of [Reliable Services](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-choose-framework#reliable-services) which is a different approach. I encourage you to see the different programming models of SF: https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-choose-framework
